language: node_js
node_js:
- '6.9.1'

cache:
  directories:
    - node_modules
    - src/node_modules

branches:
  only:
    - master

before_script:
  - npm install
  - cd src && npm install && cd ..

script:
  - npm run build

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: visualiza.tideapps.com
  skip_cleanup: true
  upload-dir: firstmakersAgent
  local_dir: build

notifications:
  email:
    on_failure: change
    on_success: change
